name: Application Deployment

on:
  push:
    branches:
      - dev
      - staging
      - main

env:
  AWS_REGION: us-east-1
  ROLE_TO_ASSUME: arn:aws:iam::${{ secrets.AWS_ACCESS_KEY_ID }}:role/GitHubAction-AssumeRoleWithAction
  ROLE_SESSION_NAME: github-workflow-role

jobs:
  build-and-deploy-to-dev-or-staging:
    runs-on: ubuntu-latest
    if: github.ref_name == 'staging' || github.ref_name == 'dev' # Only run for dev or staging

    steps:
      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variable dynamically
        id: set-env
        run: |
          echo "ENVIRONMENT=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} 
          ECR_REPOSITORY: ${{ env.ENVIRONMENT }}-spring-repo       
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f applications/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Step 6: Deploy to EKS (Optional for now)
      # - name: Update kube config
      #   env:
      #     EKS_CLUSTER_NAME: ${{ env.ENVIRONMENT }}-spring-cluster
      #   run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
        
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y jq postgresql-client
  
      # - name: Run database and secrets script
      #   run: |
      #     chmod +x ./applications/manifests/handle-secrets-and-db.sh
      #     ./applications/manifests/handle-secrets-and-db.sh

      # - name: Deploy to EKS
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: ${{ env.ENVIRONMENT }}-spring-repository        
      #     IMAGE_TAG: ${{ steps.commit.outputs.short }}
      #   run: |
      #     sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" manifests/hello-app-deployment.yaml && \
      #     kubectl apply -f manifests/hello-app-deployment.yaml
      #     kubectl apply -f manifests/hello-app-service.yaml
  build-and-deploy-to-production:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' # Only run for main

    environment:
      name: production
    steps:
      - name: Set environment variable to prod
        run: echo "ENVIRONMENT=prod" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} 
          ECR_REPOSITORY: ${{ env.ENVIRONMENT }}-spring-repo       
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f applications/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  
    # Step 6: Deploy to EKS (Optional for now)
      - name: Update kube config
        env:
          EKS_CLUSTER_NAME: ${{ env.ENVIRONMENT }}-spring-cluster
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq postgresql-client
  
      - name: Run database and secrets script
        run: |
          chmod +x ./applications/manifests/handle-secrets-and-db.sh
          ./applications/manifests/handle-secrets-and-db.sh

    # - name: Deploy to EKS
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #     ECR_REPOSITORY: ${{ env.ENVIRONMENT }}-spring-repository        
    #     IMAGE_TAG: ${{ steps.commit.outputs.short }}
    #   run: |
    #     sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" manifests/hello-app-deployment.yaml && \
    #     kubectl apply -f manifests/hello-app-deployment.yaml
    #     kubectl apply -f manifests/hello-app-service.yaml