name: Destroy

on: 
  workflow_dispatch:
    
env:
  AWS_REGION: us-east-1
  ROLE_TO_ASSUME: arn:aws:iam::${{ secrets.YOUR_AWS_ACCOUNT_ID }}:role/${{ vars.YOUR_AWS_GITHUB_ROLE }}
  ROLE_SESSION_NAME: GitHub_to_AWS_via_FederatedOIDC
  TF_VERSION: 1.9.8
  ENVIRONMENT: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}

jobs:
 destroy:
   name: "Delete infrastructure"
   runs-on: ubuntu-latest
   defaults:
      run:
        shell: bash
        working-directory: ./infrastructure
   environment:
      name: destroy
    
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
 
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: ${{env.TF_VERSION}}
         terraform_wrapper: false
    
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

     - name: Terraform init
       id: init
       run: terraform init

     - name: Terraform destroy
       id: destroy
       run: terraform destroy -var-file=${{env.ENVIRONMENT}}.tfvars --auto-approve
      